/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MemberInfo struct for MemberInfo
type MemberInfo struct {
	Id string `json:"id"`
	MentionName string `json:"mention_name"`
	Name string `json:"name"`
	Workspace2 BasicWorkspaceInfo `json:"workspace2"`
}
