/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// UpdateStory struct for UpdateStory
type UpdateStory struct {
	// The ID of the story we want to move this story after.
	AfterId int64 `json:"after_id,omitempty"`
	// True if the story is archived, otherwise false.
	Archived bool `json:"archived,omitempty"`
	// The ID of the story we want to move this story before.
	BeforeId int64 `json:"before_id,omitempty"`
	// An array of IDs of Branches attached to the story.
	BranchIds []int64 `json:"branch_ids,omitempty"`
	// An array of IDs of Commits attached to the story.
	CommitIds []int64 `json:"commit_ids,omitempty"`
	// A manual override for the time/date the Story was completed.
	CompletedAtOverride *time.Time `json:"completed_at_override,omitempty"`
	// The due date of the story.
	Deadline *time.Time `json:"deadline,omitempty"`
	// The description of the story.
	Description string `json:"description,omitempty"`
	// The ID of the epic the story belongs to.
	EpicId *int64 `json:"epic_id,omitempty"`
	// The numeric point estimate of the story. Can also be null, which means unestimated.
	Estimate *int64 `json:"estimate,omitempty"`
	// An array of IDs of files attached to the story.
	FileIds []int64 `json:"file_ids,omitempty"`
	// An array of UUIDs of the followers of this story.
	FollowerIds []string `json:"follower_ids,omitempty"`
	// The ID of the group to associate with this story
	GroupId *string `json:"group_id,omitempty"`
	// The ID of the iteration the story belongs to.
	IterationId *int64 `json:"iteration_id,omitempty"`
	// An array of labels attached to the story.
	Labels []CreateLabelParams `json:"labels,omitempty"`
	// An array of IDs of linked files attached to the story.
	LinkedFileIds []int64 `json:"linked_file_ids,omitempty"`
	MoveTo string `json:"move_to,omitempty"`
	// The title of the story.
	Name string `json:"name,omitempty"`
	// An array of UUIDs of the owners of this story.
	OwnerIds []string `json:"owner_ids,omitempty"`
	// The ID of the project the story belongs to.
	ProjectId int64 `json:"project_id,omitempty"`
	// An array of IDs of Pull/Merge Requests attached to the story.
	PullRequestIds []int64 `json:"pull_request_ids,omitempty"`
	// The ID of the member that requested the story.
	RequestedById string `json:"requested_by_id,omitempty"`
	// A manual override for the time/date the Story was started.
	StartedAtOverride *time.Time `json:"started_at_override,omitempty"`
	// The type of story (feature, bug, chore).
	StoryType string `json:"story_type,omitempty"`
	// The ID of the workflow state to put the story in.
	WorkflowStateId int64 `json:"workflow_state_id,omitempty"`
}
