/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateStoryLinkParams Request parameters for creating a Story Link within a Story.
type CreateStoryLinkParams struct {
	// The unique ID of the Story defined as object.
	ObjectId int64 `json:"object_id,omitempty"`
	// The unique ID of the Story defined as subject.
	SubjectId int64 `json:"subject_id,omitempty"`
	// How the subject Story acts on the object Story. This can be \"blocks\", \"duplicates\", or \"relates to\".
	Verb string `json:"verb"`
}
