/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ListLabels struct for ListLabels
type ListLabels struct {
	// A true/false boolean indicating if the slim versions of the Label should be returned.
	Slim bool `json:"slim,omitempty"`
}
