/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateStories struct for CreateStories
type CreateStories struct {
	// An array of stories to be created.
	Stories []CreateStoryParams `json:"stories"`
}
