/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Search struct for Search
type Search struct {
	Include string `json:"include,omitempty"`
	// The next page token.
	Next string `json:"next,omitempty"`
	// The number of search results to include in a page. Minimum of 1 and maximum of 25.
	PageSize int64 `json:"page_size,omitempty"`
	// See our help center article on [search operators](https://help.clubhouse.io/hc/en-us/articles/360000046646-Search-Operators)
	Query string `json:"query"`
}
