/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateLinkedFile struct for CreateLinkedFile
type CreateLinkedFile struct {
	// The content type of the image (e.g. txt/plain).
	ContentType string `json:"content_type,omitempty"`
	// The description of the file.
	Description string `json:"description,omitempty"`
	// The name of the file.
	Name string `json:"name"`
	// The filesize, if the integration provided it.
	Size int64 `json:"size,omitempty"`
	// The ID of the linked story.
	StoryId int64 `json:"story_id,omitempty"`
	// The URL of the thumbnail, if the integration provided it.
	ThumbnailUrl string `json:"thumbnail_url,omitempty"`
	// The integration type of the file (e.g. google, dropbox, box).
	Type string `json:"type"`
	// The UUID of the member that uploaded the file.
	UploaderId string `json:"uploader_id,omitempty"`
	// The URL of linked file.
	Url string `json:"url"`
}
