/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateLabelParams Request parameters for creating a Label on a Clubhouse story.
type CreateLabelParams struct {
	// The hex color to be displayed with the Label (for example, \"#ff0000\").
	Color string `json:"color,omitempty"`
	// The description of the new Label.
	Description string `json:"description,omitempty"`
	// This field can be set to another unique ID. In the case that the Label has been imported from another tool, the ID in the other tool can be indicated here.
	ExternalId string `json:"external_id,omitempty"`
	// The name of the new Label.
	Name string `json:"name"`
}
