/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// CreateEpic struct for CreateEpic
type CreateEpic struct {
	// A manual override for the time/date the Epic was completed.
	CompletedAtOverride time.Time `json:"completed_at_override,omitempty"`
	// Defaults to the time/date it is created but can be set to reflect another date.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The Epic's deadline.
	Deadline *time.Time `json:"deadline,omitempty"`
	// The Epic's description.
	Description string `json:"description,omitempty"`
	// The ID of the Epic State.
	EpicStateId int64 `json:"epic_state_id,omitempty"`
	// This field can be set to another unique ID. In the case that the Epic has been imported from another tool, the ID in the other tool can be indicated here.
	ExternalId string `json:"external_id,omitempty"`
	// An array of UUIDs for any Members you want to add as Followers on this new Epic.
	FollowerIds []string `json:"follower_ids,omitempty"`
	// The ID of the group to associate with the epic.
	GroupId *string `json:"group_id,omitempty"`
	// An array of Labels attached to the Epic.
	Labels []CreateLabelParams `json:"labels,omitempty"`
	// The ID of the Milestone this Epic is related to.
	MilestoneId *int64 `json:"milestone_id,omitempty"`
	// The Epic's name.
	Name string `json:"name"`
	// An array of UUIDs for any members you want to add as Owners on this new Epic.
	OwnerIds []string `json:"owner_ids,omitempty"`
	// The Epic's planned start date.
	PlannedStartDate *time.Time `json:"planned_start_date,omitempty"`
	// The ID of the member that requested the epic.
	RequestedById string `json:"requested_by_id,omitempty"`
	// A manual override for the time/date the Epic was started.
	StartedAtOverride time.Time `json:"started_at_override,omitempty"`
	// `Deprecated` The Epic's state (to do, in progress, or done); will be ignored when `epic_state_id` is set.
	State string `json:"state,omitempty"`
	// Defaults to the time/date it is created but can be set to reflect another date.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
