/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetMember struct for GetMember
type GetMember struct {
	// The unique ID of the Organization to limit the lookup to.
	OrgPublicId string `json:"org-public-id,omitempty"`
}
