/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// StoryStats The stats object for Stories
type StoryStats struct {
	// The number of documents related to this Story.
	NumRelatedDocuments int64 `json:"num_related_documents"`
}
