/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UpdateGroup struct for UpdateGroup
type UpdateGroup struct {
	// Whether or not this Group is archived.
	Archived *bool `json:"archived,omitempty"`
	// The description of this Group.
	Description string `json:"description,omitempty"`
	// The Icon id for the avatar of this Group.
	DisplayIconId *string `json:"display_icon_id,omitempty"`
	// The Member ids to add to this Group.
	MemberIds []string `json:"member_ids,omitempty"`
	// The mention name of this Group.
	MentionName string `json:"mention_name,omitempty"`
	// The name of this Group.
	Name string `json:"name,omitempty"`
}
