/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UpdateComment struct for UpdateComment
type UpdateComment struct {
	// The updated comment text.
	Text string `json:"text"`
}
