/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// StoryContents A container entity for the attributes this template should populate.
type StoryContents struct {
	// The due date of the story.
	Deadline time.Time `json:"deadline,omitempty"`
	// The description of the story.
	Description string `json:"description,omitempty"`
	// A string description of this resource.
	EntityType string `json:"entity_type,omitempty"`
	// The ID of the epic the story belongs to.
	EpicId int64 `json:"epic_id,omitempty"`
	// The numeric point estimate of the story. Can also be null, which means unestimated.
	Estimate int64 `json:"estimate,omitempty"`
	// An array of external tickets connected to the story.
	ExternalTickets []ExternalTicket `json:"external_tickets,omitempty"`
	// An array of files attached to the story.
	Files []File `json:"files,omitempty"`
	// An array of UUIDs for any Members listed as Followers.
	FollowerIds []string `json:"follower_ids,omitempty"`
	// The ID of the iteration the story belongs to.
	IterationId int64 `json:"iteration_id,omitempty"`
	// An array of labels attached to the story.
	Labels []Label `json:"labels,omitempty"`
	// An array of linked files attached to the story.
	LinkedFiles []LinkedFile `json:"linked_files,omitempty"`
	// The name of the story.
	Name string `json:"name,omitempty"`
	// An array of UUIDs of the owners of this story.
	OwnerIds []string `json:"owner_ids,omitempty"`
	// The ID of the project the story belongs to.
	ProjectId int64 `json:"project_id,omitempty"`
	// The type of story (feature, bug, chore).
	StoryType string `json:"story_type,omitempty"`
	// An array of tasks connected to the story.
	Tasks []StoryContentsTask `json:"tasks,omitempty"`
	// The ID of the workflow state the story is currently in.
	WorkflowStateId int64 `json:"workflow_state_id,omitempty"`
}
