/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UpdateStoryLink struct for UpdateStoryLink
type UpdateStoryLink struct {
	// The ID of the object Story.
	ObjectId int64 `json:"object_id,omitempty"`
	// The ID of the subject Story.
	SubjectId int64 `json:"subject_id,omitempty"`
	// The type of link.
	Verb string `json:"verb,omitempty"`
}
