/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// BasicWorkspaceInfo struct for BasicWorkspaceInfo
type BasicWorkspaceInfo struct {
	EstimateScale []int64 `json:"estimate_scale"`
	UrlSlug string `json:"url_slug"`
}
