/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateExternalTicketParams struct for CreateExternalTicketParams
type CreateExternalTicketParams struct {
	// The id of the ticket in the external system.
	ExternalId string `json:"external_id"`
	// The url for the ticket in the external system.
	ExternalUrl string `json:"external_url,omitempty"`
}
