/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateOrDeleteReaction struct for CreateOrDeleteReaction
type CreateOrDeleteReaction struct {
	// The emoji short-code to add / remove. E.g. `:thumbsup::skin-tone-4:`.
	Emoji string `json:"emoji"`
}
