/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UpdateLabel struct for UpdateLabel
type UpdateLabel struct {
	// A true/false boolean indicating if the Label has been archived.
	Archived bool `json:"archived,omitempty"`
	// The hex color to be displayed with the Label (for example, \"#ff0000\").
	Color *string `json:"color,omitempty"`
	// The new description of the label.
	Description string `json:"description,omitempty"`
	// The new name of the label.
	Name string `json:"name,omitempty"`
}
