/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ListMembers struct for ListMembers
type ListMembers struct {
	// The unique ID of the Organization to limit the list to.
	OrgPublicId string `json:"org-public-id,omitempty"`
}
