/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// PullRequest Corresponds to a VCS Pull Request attached to a Clubhouse story.
type PullRequest struct {
	// The ID of the branch for the particular pull request.
	BranchId int64 `json:"branch_id"`
	// The name of the branch for the particular pull request.
	BranchName string `json:"branch_name"`
	// The status of the Continuous Integration workflow for the pull request.
	BuildStatus string `json:"build_status,omitempty"`
	// True/False boolean indicating whether the VCS pull request has been closed.
	Closed bool `json:"closed"`
	// The time/date the pull request was created.
	CreatedAt time.Time `json:"created_at"`
	// True/False boolean indicating whether the VCS pull request is in the draft state.
	Draft bool `json:"draft"`
	// A string description of this resource.
	EntityType string `json:"entity_type"`
	// The unique ID associated with the pull request in Clubhouse.
	Id int64 `json:"id"`
	// Number of lines added in the pull request, according to VCS.
	NumAdded int64 `json:"num_added"`
	// The number of commits on the pull request.
	NumCommits *int64 `json:"num_commits"`
	// Number of lines modified in the pull request, according to VCS.
	NumModified *int64 `json:"num_modified"`
	// Number of lines removed in the pull request, according to VCS.
	NumRemoved int64 `json:"num_removed"`
	// The pull requests unique number ID in VCS.
	Number int64 `json:"number"`
	// The status of the review for the pull request.
	ReviewStatus string `json:"review_status,omitempty"`
	// The ID of the target branch for the particular pull request.
	TargetBranchId int64 `json:"target_branch_id"`
	// The name of the target branch for the particular pull request.
	TargetBranchName string `json:"target_branch_name"`
	// The title of the pull request.
	Title string `json:"title"`
	// The time/date the pull request was created.
	UpdatedAt time.Time `json:"updated_at"`
	// The URL for the pull request.
	Url string `json:"url"`
	// An array of PullRequestLabels attached to the PullRequest.
	VcsLabels *[]PullRequestLabel `json:"vcs_labels,omitempty"`
}
