/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateEntityTemplate Request paramaters for creating an entirely new entity template.
type CreateEntityTemplate struct {
	// The id of the user creating this template.
	AuthorId string `json:"author_id,omitempty"`
	// The name of the new entity template
	Name string `json:"name"`
	StoryContents CreateStoryContents `json:"story_contents"`
}
