/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// Icon Icons are used to attach images to Organizations, Members, and Loading screens in the Clubhouse web application.
type Icon struct {
	// The time/date that the Icon was created.
	CreatedAt time.Time `json:"created_at"`
	// A string description of this resource.
	EntityType string `json:"entity_type"`
	// The unique ID of the Icon.
	Id string `json:"id"`
	// The time/date that the Icon was updated.
	UpdatedAt time.Time `json:"updated_at"`
	// The URL of the Icon.
	Url string `json:"url"`
}
