/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateFiles struct for CreateFiles
type CreateFiles struct {
	// The story ID that this file will be associated with.
	StoryId int64 `json:"story_id,omitempty"`
}
