/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UpdateLinkedFile struct for UpdateLinkedFile
type UpdateLinkedFile struct {
	// The description of the file.
	Description string `json:"description,omitempty"`
	// The name of the file.
	Name string `json:"name,omitempty"`
	// The filesize, if the integration provided it.
	Size int64 `json:"size,omitempty"`
	// The ID of the linked story.
	StoryId int64 `json:"story_id,omitempty"`
	// The URL of the thumbnail, if the integration provided it.
	ThumbnailUrl string `json:"thumbnail_url,omitempty"`
	// The integration type of the file (e.g. google, dropbox, box).
	Type string `json:"type,omitempty"`
	// The UUID of the member that uploaded the file.
	UploaderId string `json:"uploader_id,omitempty"`
	// The URL of linked file.
	Url string `json:"url,omitempty"`
}
