/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UpdateTask struct for UpdateTask
type UpdateTask struct {
	// Move task after this task ID.
	AfterId int64 `json:"after_id,omitempty"`
	// Move task before this task ID.
	BeforeId int64 `json:"before_id,omitempty"`
	// A true/false boolean indicating whether the task is complete.
	Complete bool `json:"complete,omitempty"`
	// The Task's description.
	Description string `json:"description,omitempty"`
	// An array of UUIDs of the owners of this story.
	OwnerIds []string `json:"owner_ids,omitempty"`
}
