/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateCategoryParams Request parameters for creating a Category with a Milestone.
type CreateCategoryParams struct {
	// The hex color to be displayed with the Category (for example, \"#ff0000\").
	Color string `json:"color,omitempty"`
	// This field can be set to another unique ID. In the case that the Category has been imported from another tool, the ID in the other tool can be indicated here.
	ExternalId string `json:"external_id,omitempty"`
	// The name of the new Category.
	Name string `json:"name"`
}
