/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateStoryLink struct for CreateStoryLink
type CreateStoryLink struct {
	// The ID of the object Story.
	ObjectId int64 `json:"object_id"`
	// The ID of the subject Story.
	SubjectId int64 `json:"subject_id"`
	// The type of link.
	Verb string `json:"verb"`
}
