/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UpdateCategory struct for UpdateCategory
type UpdateCategory struct {
	// A true/false boolean indicating if the Category has been archived.
	Archived bool `json:"archived,omitempty"`
	// The hex color to be displayed with the Category (for example, \"#ff0000\").
	Color *string `json:"color,omitempty"`
	// The new name of the Category.
	Name string `json:"name,omitempty"`
}
