/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DeleteStories struct for DeleteStories
type DeleteStories struct {
	// An array of IDs of Stories to delete.
	StoryIds []int64 `json:"story_ids"`
}
