/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Identity The Identity of the VCS user that authored the Commit.
type Identity struct {
	// A string description of this resource.
	EntityType string `json:"entity_type"`
	// This is your login in VCS.
	Name *string `json:"name"`
	// The type of Identity; currently only type is github.
	Type *string `json:"type"`
}
