/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UpdateEntityTemplate Request parameters for changing either a template's name or any of   the attributes it is designed to pre-populate.
type UpdateEntityTemplate struct {
	// The updated template name.
	Name string `json:"name,omitempty"`
	StoryContents CreateStoryContents `json:"story_contents,omitempty"`
}
