/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// CreateMilestone struct for CreateMilestone
type CreateMilestone struct {
	// An array of IDs of Categories attached to the Milestone.
	Categories []CreateCategoryParams `json:"categories,omitempty"`
	// A manual override for the time/date the Milestone was completed.
	CompletedAtOverride time.Time `json:"completed_at_override,omitempty"`
	// The Milestone's description.
	Description string `json:"description,omitempty"`
	// The name of the Milestone.
	Name string `json:"name"`
	// A manual override for the time/date the Milestone was started.
	StartedAtOverride time.Time `json:"started_at_override,omitempty"`
	// The workflow state that the Milestone is in.
	State string `json:"state,omitempty"`
}
