/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ListEpics struct for ListEpics
type ListEpics struct {
	// A true/false boolean indicating whether to return Epics with their descriptions.
	IncludesDescription bool `json:"includes_description,omitempty"`
}
