/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// LabelStats A group of calculated values for this Label.
type LabelStats struct {
	// The total number of Epics with this Label.
	NumEpics int64 `json:"num_epics"`
	// The total number of completed points with this Label.
	NumPointsCompleted int64 `json:"num_points_completed"`
	// The total number of in-progress points with this Label.
	NumPointsInProgress int64 `json:"num_points_in_progress"`
	// The total number of points with this Label.
	NumPointsTotal int64 `json:"num_points_total"`
	// The total number of Documents associated this Label.
	NumRelatedDocuments int64 `json:"num_related_documents"`
	// The total number of completed Stories with this Label.
	NumStoriesCompleted int64 `json:"num_stories_completed"`
	// The total number of in-progress Stories with this Label.
	NumStoriesInProgress int64 `json:"num_stories_in_progress"`
	// The total number of Stories with this Label.
	NumStoriesTotal int64 `json:"num_stories_total"`
	// The total number of Stories with no point estimate with this Label.
	NumStoriesUnestimated int64 `json:"num_stories_unestimated"`
}
