/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CreateGroup struct for CreateGroup
type CreateGroup struct {
	// The description of the Group.
	Description string `json:"description,omitempty"`
	// The Icon id for the avatar of this Group.
	DisplayIconId string `json:"display_icon_id,omitempty"`
	// The Member ids to add to this Group.
	MemberIds []string `json:"member_ids,omitempty"`
	// The mention name of this Group.
	MentionName string `json:"mention_name"`
	// The name of this Group.
	Name string `json:"name"`
}
