/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// UpdateFile struct for UpdateFile
type UpdateFile struct {
	// The time/date that the file was uploaded.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The description of the file.
	Description string `json:"description,omitempty"`
	// An additional ID that you may wish to assign to the file.
	ExternalId string `json:"external_id,omitempty"`
	// The name of the file.
	Name string `json:"name,omitempty"`
	// The time/date that the file was last updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// The unique ID assigned to the Member who uploaded the file to Clubhouse.
	UploaderId string `json:"uploader_id,omitempty"`
}
