/*
 * Clubhouse API
 *
 * Clubhouse API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ExternalTicket A External Ticket allows you to create a link between an external system, like Zendesk, and a Clubhouse story.
type ExternalTicket struct {
	// The ID used in the external system.
	ExternalId string `json:"external_id"`
	// The full qualified url of the external ticket.
	ExternalUrl string `json:"external_url,omitempty"`
	// A unique ID internal to Clubhouse.
	Id string `json:"id"`
	// The Clubhouse Story ids associated with this External Ticket.
	StoryIds []float64 `json:"story_ids"`
}
